name: dev

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  deploy:
    runs-on: [dev]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: run install, build and test
        run: |
          cd /opt/apps
          rm -rf classificador-especializada
          git clone --branch dev --single-branch git@github.com:LINK DO PROJETO
          cd classificador-especializada
          chmod +x ./build.sh
          ./build.sh